/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/dollar.glb -o src/components/Dollar.tsx -r public 
*/

import { useEffect, useRef } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import type { ThreeElements } from '@react-three/fiber'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Text001: THREE.Mesh
    Text002: THREE.Mesh
    Text003: THREE.Mesh
    Text004: THREE.Mesh
    Text005: THREE.Mesh
    Text006: THREE.Mesh
    Text007: THREE.Mesh
    Text008: THREE.Mesh
    Text009: THREE.Mesh
    Text010: THREE.Mesh
    Text011: THREE.Mesh
    Text012: THREE.Mesh
    Text013: THREE.Mesh
    Text014: THREE.Mesh
    Text015: THREE.Mesh
    Text016: THREE.Mesh
    Text017: THREE.Mesh
    Text018: THREE.Mesh
    Text019: THREE.Mesh
    Text020: THREE.Mesh
    Text021: THREE.Mesh
    Text022: THREE.Mesh
    Text023: THREE.Mesh
    Text024: THREE.Mesh
    Text025: THREE.Mesh
    Text026: THREE.Mesh
    Text027: THREE.Mesh
    Text028: THREE.Mesh
    Text029: THREE.Mesh
    Text030: THREE.Mesh
    Text031: THREE.Mesh
    Text032: THREE.Mesh
    Text034: THREE.Mesh
    Text035: THREE.Mesh
    Text036: THREE.Mesh
    Text037: THREE.Mesh
    Text038: THREE.Mesh
    Text039: THREE.Mesh
    Text042: THREE.Mesh
    Text043: THREE.Mesh
    Text044: THREE.Mesh
    Text045: THREE.Mesh
    Text046: THREE.Mesh
    Text047: THREE.Mesh
    Text048: THREE.Mesh
    Text049: THREE.Mesh
    Text050: THREE.Mesh
    Text051: THREE.Mesh
    Text052: THREE.Mesh
    Text053: THREE.Mesh
    Text054: THREE.Mesh
    Text055: THREE.Mesh
    Text056: THREE.Mesh
    Text057: THREE.Mesh
    Text058: THREE.Mesh
    Text059: THREE.Mesh
    Text060: THREE.Mesh
    Text061: THREE.Mesh
    Text062: THREE.Mesh
    Text063: THREE.Mesh
    Text065: THREE.Mesh
    Text066: THREE.Mesh
    Text067: THREE.Mesh
    Text068: THREE.Mesh
    Text069: THREE.Mesh
    Text070: THREE.Mesh
    Text071: THREE.Mesh
    Text072: THREE.Mesh
    Text073: THREE.Mesh
    Text074: THREE.Mesh
    Text075: THREE.Mesh
    Text076: THREE.Mesh
    Text077: THREE.Mesh
    Text078: THREE.Mesh
    Text079: THREE.Mesh
    Text080: THREE.Mesh
    Text081: THREE.Mesh
    Text082: THREE.Mesh
    Text083: THREE.Mesh
    Text084: THREE.Mesh
    Text086: THREE.Mesh
    Text087: THREE.Mesh
    Text090: THREE.Mesh
    Text091: THREE.Mesh
    Text092: THREE.Mesh
    Text093: THREE.Mesh
    Text094: THREE.Mesh
    Text095: THREE.Mesh
    Text096: THREE.Mesh
    Text098: THREE.Mesh
    Text099: THREE.Mesh
    Text100: THREE.Mesh
    Text101: THREE.Mesh
    Text102: THREE.Mesh
    Text104: THREE.Mesh
    Text105: THREE.Mesh
    Text106: THREE.Mesh
    Text108: THREE.Mesh
    Text109: THREE.Mesh
    Text110: THREE.Mesh
    Text111: THREE.Mesh
    Text112: THREE.Mesh
    Text113: THREE.Mesh
    Text114: THREE.Mesh
    Text115: THREE.Mesh
    Text116: THREE.Mesh
    Text118: THREE.Mesh
    Text119: THREE.Mesh
    Text120: THREE.Mesh
    Text121: THREE.Mesh
    Text122: THREE.Mesh
    Text124: THREE.Mesh
    Text125: THREE.Mesh
    Text126: THREE.Mesh
    Text128: THREE.Mesh
    Text129: THREE.Mesh
    Text130: THREE.Mesh
    Text131: THREE.Mesh
    Text132: THREE.Mesh
    Text133: THREE.Mesh
    Text134: THREE.Mesh
    Text135: THREE.Mesh
    Text136: THREE.Mesh
    Text137: THREE.Mesh
    Text138: THREE.Mesh
    Text139: THREE.Mesh
    Text140: THREE.Mesh
    Text141: THREE.Mesh
    Text142: THREE.Mesh
    Text143: THREE.Mesh
    Text144: THREE.Mesh
    Text145: THREE.Mesh
    Text146: THREE.Mesh
    Text147: THREE.Mesh
    Text148: THREE.Mesh
    Text149: THREE.Mesh
    Text150: THREE.Mesh
    Text151: THREE.Mesh
    Text152: THREE.Mesh
    Text153: THREE.Mesh
    Text154: THREE.Mesh
    Text155: THREE.Mesh
    Text157: THREE.Mesh
    Text158: THREE.Mesh
    Text159: THREE.Mesh
    Text160: THREE.Mesh
    Text161: THREE.Mesh
    Text162: THREE.Mesh
    Text163: THREE.Mesh
    Text164: THREE.Mesh
    Text165: THREE.Mesh
    Text166: THREE.Mesh
    Text167: THREE.Mesh
    Text168: THREE.Mesh
    Text169: THREE.Mesh
    Text170: THREE.Mesh
    Text171: THREE.Mesh
    Text172: THREE.Mesh
    Text173: THREE.Mesh
    Text174: THREE.Mesh
    Text175: THREE.Mesh
    Text176: THREE.Mesh
    Text177: THREE.Mesh
    Text178: THREE.Mesh
    Text179: THREE.Mesh
    Text180: THREE.Mesh
    Text181: THREE.Mesh
    Text182: THREE.Mesh
    Text183: THREE.Mesh
    Text184: THREE.Mesh
    Text185: THREE.Mesh
    Text186: THREE.Mesh
    Text187: THREE.Mesh
    Text188: THREE.Mesh
    Text189: THREE.Mesh
    Text190: THREE.Mesh
    Text191: THREE.Mesh
    Text192: THREE.Mesh
    Text193: THREE.Mesh
    Text194: THREE.Mesh
    Text195: THREE.Mesh
    Text196: THREE.Mesh
    Text197: THREE.Mesh
    Text198: THREE.Mesh
    Text199: THREE.Mesh
    Text200: THREE.Mesh
    Text201: THREE.Mesh
    Text202: THREE.Mesh
    Text203: THREE.Mesh
    Text204: THREE.Mesh
    Text205: THREE.Mesh
    Text206: THREE.Mesh
    Text207: THREE.Mesh
    Text208: THREE.Mesh
    Text209: THREE.Mesh
    Text210: THREE.Mesh
    Text211: THREE.Mesh
    Text212: THREE.Mesh
    Text213: THREE.Mesh
    Text214: THREE.Mesh
    Text215: THREE.Mesh
    Text216: THREE.Mesh
    Text217: THREE.Mesh
    Text218: THREE.Mesh
    Text219: THREE.Mesh
    Text220: THREE.Mesh
    Text221: THREE.Mesh
    Text222: THREE.Mesh
    Text223: THREE.Mesh
    Text224: THREE.Mesh
    Text225: THREE.Mesh
    Text226: THREE.Mesh
    Text227: THREE.Mesh
    Text228: THREE.Mesh
    Text229: THREE.Mesh
    Text230: THREE.Mesh
    Text231: THREE.Mesh
    Text232: THREE.Mesh
    Text233: THREE.Mesh
    Text234: THREE.Mesh
    Text235: THREE.Mesh
    Text236: THREE.Mesh
    Text237: THREE.Mesh
    Text238: THREE.Mesh
    Text239: THREE.Mesh
    Text240: THREE.Mesh
    Text241: THREE.Mesh
    Text242: THREE.Mesh
    Text243: THREE.Mesh
    Text244: THREE.Mesh
    Text245: THREE.Mesh
    Text246: THREE.Mesh
    Text247: THREE.Mesh
    Text248: THREE.Mesh
    Text249: THREE.Mesh
    Text250: THREE.Mesh
    Text251: THREE.Mesh
    Text252: THREE.Mesh
    Text253: THREE.Mesh
    Text254: THREE.Mesh
    Text255: THREE.Mesh
    Text256: THREE.Mesh
    Text257: THREE.Mesh
    Text258: THREE.Mesh
    Text259: THREE.Mesh
    Text260: THREE.Mesh
    Text261: THREE.Mesh
    Text262: THREE.Mesh
    Text263: THREE.Mesh
    Text264: THREE.Mesh
    Text265: THREE.Mesh
    Text266: THREE.Mesh
    Text267: THREE.Mesh
    Text268: THREE.Mesh
    Text269: THREE.Mesh
    Text270: THREE.Mesh
    Text271: THREE.Mesh
    Text272: THREE.Mesh
    Text273: THREE.Mesh
    Text274: THREE.Mesh
    Text275: THREE.Mesh
    Text276: THREE.Mesh
    Text277: THREE.Mesh
    Text278: THREE.Mesh
    Text279: THREE.Mesh
    Text280: THREE.Mesh
    Text281: THREE.Mesh
    Text282: THREE.Mesh
    Text283: THREE.Mesh
    Text284: THREE.Mesh
    Text285: THREE.Mesh
    Text286: THREE.Mesh
    Text287: THREE.Mesh
    Text288: THREE.Mesh
    Text289: THREE.Mesh
    Text290: THREE.Mesh
    Text291: THREE.Mesh
    Text292: THREE.Mesh
    Text293: THREE.Mesh
    Text294: THREE.Mesh
    Text295: THREE.Mesh
    Text296: THREE.Mesh
    Text297: THREE.Mesh
    Text298: THREE.Mesh
    Text299: THREE.Mesh
    Text300: THREE.Mesh
    Text301: THREE.Mesh
    Text302: THREE.Mesh
    Text303: THREE.Mesh
    Text304: THREE.Mesh
    Text305: THREE.Mesh
    Text306: THREE.Mesh
    Text307: THREE.Mesh
    Text308: THREE.Mesh
    Text309: THREE.Mesh
    Text310: THREE.Mesh
    Text311: THREE.Mesh
    Text312: THREE.Mesh
    Text313: THREE.Mesh
    Text314: THREE.Mesh
    Text315: THREE.Mesh
    Text316: THREE.Mesh
    Text317: THREE.Mesh
    Text318: THREE.Mesh
    Text319: THREE.Mesh
    Text320: THREE.Mesh
    Text321: THREE.Mesh
    Text322: THREE.Mesh
    Text323: THREE.Mesh
    Text324: THREE.Mesh
    Text325: THREE.Mesh
    Text326: THREE.Mesh
    Text327: THREE.Mesh
    Text328: THREE.Mesh
    Text329: THREE.Mesh
    Text330: THREE.Mesh
    Text331: THREE.Mesh
    Text332: THREE.Mesh
    Text333: THREE.Mesh
    Text334: THREE.Mesh
    Text335: THREE.Mesh
    Text336: THREE.Mesh
    Text337: THREE.Mesh
    Text338: THREE.Mesh
    Text339: THREE.Mesh
    Text340: THREE.Mesh
    Text341: THREE.Mesh
    Text342: THREE.Mesh
    Text343: THREE.Mesh
    Text344: THREE.Mesh
    Text345: THREE.Mesh
    Text346: THREE.Mesh
    Text347: THREE.Mesh
    Text348: THREE.Mesh
    Text349: THREE.Mesh
    Text350: THREE.Mesh
    Text351: THREE.Mesh
    Text352: THREE.Mesh
    Text353: THREE.Mesh
    Text354: THREE.Mesh
    Text355: THREE.Mesh
    Text356: THREE.Mesh
    Text357: THREE.Mesh
    Text358: THREE.Mesh
    Text359: THREE.Mesh
    Text360: THREE.Mesh
    Text361: THREE.Mesh
    Text362: THREE.Mesh
    Text363: THREE.Mesh
    Text364: THREE.Mesh
    Text365: THREE.Mesh
    Text366: THREE.Mesh
    Text367: THREE.Mesh
    Text368: THREE.Mesh
    Text369: THREE.Mesh
    Text370: THREE.Mesh
    Text371: THREE.Mesh
    Text372: THREE.Mesh
    Text373: THREE.Mesh
    Text374: THREE.Mesh
    Text375: THREE.Mesh
    Text376: THREE.Mesh
    Text377: THREE.Mesh
    Text378: THREE.Mesh
    Text379: THREE.Mesh
    Text380: THREE.Mesh
    Text381: THREE.Mesh
    Text382: THREE.Mesh
    Text383: THREE.Mesh
    Text384: THREE.Mesh
    Text385: THREE.Mesh
    Text386: THREE.Mesh
    Text387: THREE.Mesh
    Text388: THREE.Mesh
    Text389: THREE.Mesh
    Text390: THREE.Mesh
    Text391: THREE.Mesh
    Text392: THREE.Mesh
    Text393: THREE.Mesh
    Text394: THREE.Mesh
    Text395: THREE.Mesh
    Text396: THREE.Mesh
    Text397: THREE.Mesh
    Text398: THREE.Mesh
    Text399: THREE.Mesh
    Text400: THREE.Mesh
    Text401: THREE.Mesh
    Text402: THREE.Mesh
    Text403: THREE.Mesh
    Text404: THREE.Mesh
    Text405: THREE.Mesh
    Text406: THREE.Mesh
    Text407: THREE.Mesh
    Text408: THREE.Mesh
    Text409: THREE.Mesh
    Text410: THREE.Mesh
    Text411: THREE.Mesh
    Text412: THREE.Mesh
    Text413: THREE.Mesh
    Text414: THREE.Mesh
    Text415: THREE.Mesh
    Text416: THREE.Mesh
    Text417: THREE.Mesh
    Text418: THREE.Mesh
    Text419: THREE.Mesh
    Text420: THREE.Mesh
    Text421: THREE.Mesh
    Text422: THREE.Mesh
    Text423: THREE.Mesh
    Text424: THREE.Mesh
    Text425: THREE.Mesh
    Text426: THREE.Mesh
    Text427: THREE.Mesh
    Text428: THREE.Mesh
    Text429: THREE.Mesh
    Text430: THREE.Mesh
    Text431: THREE.Mesh
    Text432: THREE.Mesh
    Text433: THREE.Mesh
    Text434: THREE.Mesh
    Text435: THREE.Mesh
    Text436: THREE.Mesh
    Text437: THREE.Mesh
    Text438: THREE.Mesh
    Text439: THREE.Mesh
    Text440: THREE.Mesh
    Text441: THREE.Mesh
    Text442: THREE.Mesh
    Text443: THREE.Mesh
    Text444: THREE.Mesh
    Text445: THREE.Mesh
    Text446: THREE.Mesh
    Text448: THREE.Mesh
    Text449: THREE.Mesh
    Text450: THREE.Mesh
    Text451: THREE.Mesh
    Text452: THREE.Mesh
    Text453: THREE.Mesh
    Text454: THREE.Mesh
    Text455: THREE.Mesh
    Text456: THREE.Mesh
    Text457: THREE.Mesh
    Text458: THREE.Mesh
    Text459: THREE.Mesh
    Text460: THREE.Mesh
    Text461: THREE.Mesh
    Text462: THREE.Mesh
    Text463: THREE.Mesh
    Text464: THREE.Mesh
    Text465: THREE.Mesh
    Text466: THREE.Mesh
    Text467: THREE.Mesh
    Text468: THREE.Mesh
    Text469: THREE.Mesh
    Text470: THREE.Mesh
    Text471: THREE.Mesh
    Text475: THREE.Mesh
    Text476: THREE.Mesh
    Text477: THREE.Mesh
    Text478: THREE.Mesh
    Text479: THREE.Mesh
    Text480: THREE.Mesh
    Text481: THREE.Mesh
    Text482: THREE.Mesh
    Text483: THREE.Mesh
    Text484: THREE.Mesh
    Text485: THREE.Mesh
    Text486: THREE.Mesh
    Text487: THREE.Mesh
    Text488: THREE.Mesh
    Text489: THREE.Mesh
    Text490: THREE.Mesh
    Text491: THREE.Mesh
    Text492: THREE.Mesh
    Text493: THREE.Mesh
    Text494: THREE.Mesh
    Text495: THREE.Mesh
    Text496: THREE.Mesh
    Text497: THREE.Mesh
    Text498: THREE.Mesh
    Text499: THREE.Mesh
    Text501: THREE.Mesh
    Text502: THREE.Mesh
    Text503: THREE.Mesh
    Text504: THREE.Mesh
    Text505: THREE.Mesh
    Text506: THREE.Mesh
    Text507: THREE.Mesh
    Text508: THREE.Mesh
    Text509: THREE.Mesh
    Text510: THREE.Mesh
    Text511: THREE.Mesh
    Text512: THREE.Mesh
    Text513: THREE.Mesh
    Text514: THREE.Mesh
    Text515: THREE.Mesh
    Text516: THREE.Mesh
    Text517: THREE.Mesh
    Text518: THREE.Mesh
    Text519: THREE.Mesh
    Text520: THREE.Mesh
    Text521: THREE.Mesh
    Text522: THREE.Mesh
    Text526: THREE.Mesh
    Text527: THREE.Mesh
    Text528: THREE.Mesh
    Text529: THREE.Mesh
    Text530: THREE.Mesh
    Text531: THREE.Mesh
    Text532: THREE.Mesh
    Text533: THREE.Mesh
    Text534: THREE.Mesh
    Text535: THREE.Mesh
    Text536: THREE.Mesh
    Text537: THREE.Mesh
    Text538: THREE.Mesh
    Text539: THREE.Mesh
    Text540: THREE.Mesh
    Text541: THREE.Mesh
  }
  materials: {}
}

export function Model(props: ThreeElements['group']) {
  type AnimatedMesh = {
    mesh: THREE.Mesh
    originalPosition: THREE.Vector3
    originalGroupCenter: THREE.Vector3
    originalWorldCenter: THREE.Vector3
    targetPosition: THREE.Vector3
    pushDirection: THREE.Vector3
  }
  const { nodes } = useGLTF(`${import.meta.env.BASE_URL}models/dollar.glb`) as unknown as GLTFResult
  const groupRef = useRef<THREE.Group>(null)
  const meshesRef = useRef<AnimatedMesh[]>([])
  const rotationVelocity = useRef({
    y: (Math.random() < 0.5 ? -1 : 1) * 0.12,
    z: (Math.random() * 2 - 1) * 0.015,
  })
  const initialZRotation = useRef<number | null>(null)
  const zDrift = useRef(0)

  const mouseWorld = useRef(new THREE.Vector3())
  const interactionPlane = useRef(new THREE.Plane())
  const planeNormal = useRef(new THREE.Vector3())
  const modelWorldPosition = useRef(new THREE.Vector3())
  const inverseParentMatrix = useRef(new THREE.Matrix4())
  const lastPointerMoveAt = useRef(Number.NEGATIVE_INFINITY)
  const interactionStrength = useRef(0)
  const interactionWasRunning = useRef(false)

  const { camera, gl, pointer, raycaster } = useThree()

  const effectRadius = .15
  const pushStrength = .3
  const returnSpeed = 3

  useEffect(() => {
    const canvas = gl.domElement
    const markPointerActive = () => {
      lastPointerMoveAt.current = performance.now()
    }
    const stopPointerInteraction = () => {
      lastPointerMoveAt.current = Number.NEGATIVE_INFINITY
    }

    canvas.addEventListener('pointermove', markPointerActive, {
      passive: true,
    })
    canvas.addEventListener('pointerleave', stopPointerInteraction)

    return () => {
      canvas.removeEventListener('pointermove', markPointerActive)
      canvas.removeEventListener(
        'pointerleave',
        stopPointerInteraction,
      )
    }
  }, [gl])

  useEffect(() => {
    if (!groupRef.current) return

    groupRef.current.updateWorldMatrix(true, true)

    // Your generated GLTF nests all of the other meshes inside Text001.
    // Move those nested meshes directly into the main group so every
    // mesh can move independently.
    const nestedMeshes: THREE.Mesh[] = []

    groupRef.current.traverse((object) => {
      if (
        object instanceof THREE.Mesh &&
        object.parent instanceof THREE.Mesh
      ) {
        nestedMeshes.push(object)
      }
    })

    for (const mesh of nestedMeshes) {
      groupRef.current.attach(mesh)
    }

    groupRef.current.updateWorldMatrix(true, true)

    const meshes: AnimatedMesh[] = []

    groupRef.current.traverse((object) => {
      if (!(object instanceof THREE.Mesh)) return

      if (!object.geometry.boundingBox) {
        object.geometry.computeBoundingBox()
      }

      const geometryCenter = new THREE.Vector3()
      object.geometry.boundingBox?.getCenter(geometryCenter)
      const originalWorldCenter = geometryCenter.clone()
      object.localToWorld(originalWorldCenter)
      const originalGroupCenter = originalWorldCenter.clone()
      groupRef.current?.worldToLocal(originalGroupCenter)

      meshes.push({
        mesh: object,
        originalPosition: object.position.clone(),
        originalGroupCenter,
        originalWorldCenter,
        targetPosition: object.position.clone(),
        pushDirection: new THREE.Vector3(),
      })
    })

    meshesRef.current = meshes
  }, [])

  useFrame((_, delta) => {
    if (!groupRef.current) return

    if (initialZRotation.current === null) {
      initialZRotation.current = groupRef.current.rotation.z
    }

    const zDriftLimit = 0.15
    zDrift.current += delta * rotationVelocity.current.z

    if (Math.abs(zDrift.current) >= zDriftLimit) {
      zDrift.current = THREE.MathUtils.clamp(
        zDrift.current,
        -zDriftLimit,
        zDriftLimit,
      )
      rotationVelocity.current.z *= -1
    }

    groupRef.current.rotation.y += delta * rotationVelocity.current.y
    groupRef.current.rotation.z =
      initialZRotation.current + zDrift.current

    const smoothing = 1 - Math.exp(-returnSpeed * delta)
    const pointerIsActive =
      performance.now() - lastPointerMoveAt.current < 500
    const interactionSmoothing =
      1 - Math.exp(-(pointerIsActive ? 5 : 8) * delta)

    interactionStrength.current = THREE.MathUtils.lerp(
      interactionStrength.current,
      pointerIsActive ? 1 : 0,
      interactionSmoothing,
    )

    const interactionIsRunning =
      pointerIsActive || interactionStrength.current > 0.001

    if (!interactionIsRunning) {
      if (!interactionWasRunning.current) return

      let meshesAreSettled = true

      for (const item of meshesRef.current) {
        item.mesh.position.lerp(item.originalPosition, smoothing)

        if (
          item.mesh.position.distanceToSquared(item.originalPosition) >
          0.00000001
        ) {
          meshesAreSettled = false
        } else {
          item.mesh.position.copy(item.originalPosition)
        }
      }

      interactionWasRunning.current = !meshesAreSettled
      return
    }

    interactionWasRunning.current = true
    groupRef.current.updateWorldMatrix(true, true)
    groupRef.current.getWorldPosition(modelWorldPosition.current)
    camera.getWorldDirection(planeNormal.current)

    interactionPlane.current.setFromNormalAndCoplanarPoint(
      planeNormal.current,
      modelWorldPosition.current,
    )

    raycaster.setFromCamera(pointer, camera)

    const mouseHit = raycaster.ray.intersectPlane(
      interactionPlane.current,
      mouseWorld.current,
    )
    const effectRadiusSquared = effectRadius * effectRadius

    for (const item of meshesRef.current) {
      const {
        mesh,
        originalPosition,
        originalGroupCenter,
        originalWorldCenter,
        targetPosition,
        pushDirection,
      } = item

      originalWorldCenter.copy(originalGroupCenter)
      groupRef.current.localToWorld(originalWorldCenter)
      targetPosition.copy(originalPosition)

      if (mouseHit && pointerIsActive) {
        const dx =
          originalWorldCenter.x - mouseWorld.current.x
        const dy =
          originalWorldCenter.y - mouseWorld.current.y
        const distanceSquared = dx * dx + dy * dy

        if (
          distanceSquared < effectRadiusSquared &&
          distanceSquared > 0.000001
        ) {
          const distance = Math.sqrt(distanceSquared)
          const force = 1 - distance / effectRadius
          const repulsion =
            pushStrength * force * interactionStrength.current

          pushDirection.set(dx / distance, dy / distance, 0)

          if (mesh.parent) {
            inverseParentMatrix.current
              .copy(mesh.parent.matrixWorld)
              .invert()

            pushDirection.transformDirection(
              inverseParentMatrix.current,
            )
          }

          pushDirection.multiplyScalar(repulsion)

          targetPosition.add(pushDirection)
          targetPosition.z += repulsion * 0.35
        }
      }

      mesh.position.lerp(targetPosition, smoothing)
    }
  })
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[0.021, 0.67, -0.024]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Text002.geometry} material={nodes.Text002.material} />
        <mesh geometry={nodes.Text003.geometry} material={nodes.Text003.material} />
        <mesh geometry={nodes.Text004.geometry} material={nodes.Text004.material} />
        <mesh geometry={nodes.Text005.geometry} material={nodes.Text005.material} />
        <mesh geometry={nodes.Text006.geometry} material={nodes.Text006.material} />
        <mesh geometry={nodes.Text007.geometry} material={nodes.Text007.material} />
        <mesh geometry={nodes.Text008.geometry} material={nodes.Text008.material} />
        <mesh geometry={nodes.Text009.geometry} material={nodes.Text009.material} />
        <mesh geometry={nodes.Text010.geometry} material={nodes.Text010.material} />
        <mesh geometry={nodes.Text011.geometry} material={nodes.Text011.material} />
        <mesh geometry={nodes.Text012.geometry} material={nodes.Text012.material} />
        <mesh geometry={nodes.Text013.geometry} material={nodes.Text013.material} />
        <mesh geometry={nodes.Text014.geometry} material={nodes.Text014.material} />
        <mesh geometry={nodes.Text015.geometry} material={nodes.Text015.material} />
        <mesh geometry={nodes.Text016.geometry} material={nodes.Text016.material} />
        <mesh geometry={nodes.Text017.geometry} material={nodes.Text017.material} />
        <mesh geometry={nodes.Text018.geometry} material={nodes.Text018.material} />
        <mesh geometry={nodes.Text019.geometry} material={nodes.Text019.material} />
        <mesh geometry={nodes.Text020.geometry} material={nodes.Text020.material} />
        <mesh geometry={nodes.Text021.geometry} material={nodes.Text021.material} />
        <mesh geometry={nodes.Text022.geometry} material={nodes.Text022.material} />
        <mesh geometry={nodes.Text023.geometry} material={nodes.Text023.material} />
        <mesh geometry={nodes.Text024.geometry} material={nodes.Text024.material} />
        <mesh geometry={nodes.Text025.geometry} material={nodes.Text025.material} />
        <mesh geometry={nodes.Text026.geometry} material={nodes.Text026.material} />
        <mesh geometry={nodes.Text027.geometry} material={nodes.Text027.material} />
        <mesh geometry={nodes.Text028.geometry} material={nodes.Text028.material} />
        <mesh geometry={nodes.Text029.geometry} material={nodes.Text029.material} />
        <mesh geometry={nodes.Text030.geometry} material={nodes.Text030.material} />
        <mesh geometry={nodes.Text031.geometry} material={nodes.Text031.material} />
        <mesh geometry={nodes.Text032.geometry} material={nodes.Text032.material} />
        <mesh geometry={nodes.Text034.geometry} material={nodes.Text034.material} />
        <mesh geometry={nodes.Text035.geometry} material={nodes.Text035.material} />
        <mesh geometry={nodes.Text036.geometry} material={nodes.Text036.material} />
        <mesh geometry={nodes.Text037.geometry} material={nodes.Text037.material} />
        <mesh geometry={nodes.Text038.geometry} material={nodes.Text038.material} />
        <mesh geometry={nodes.Text039.geometry} material={nodes.Text039.material} />
        <mesh geometry={nodes.Text042.geometry} material={nodes.Text042.material} />
        <mesh geometry={nodes.Text043.geometry} material={nodes.Text043.material} />
        <mesh geometry={nodes.Text044.geometry} material={nodes.Text044.material} />
        <mesh geometry={nodes.Text045.geometry} material={nodes.Text045.material} />
        <mesh geometry={nodes.Text046.geometry} material={nodes.Text046.material} />
        <mesh geometry={nodes.Text047.geometry} material={nodes.Text047.material} />
        <mesh geometry={nodes.Text048.geometry} material={nodes.Text048.material} />
        <mesh geometry={nodes.Text049.geometry} material={nodes.Text049.material} />
        <mesh geometry={nodes.Text050.geometry} material={nodes.Text050.material} />
        <mesh geometry={nodes.Text051.geometry} material={nodes.Text051.material} />
        <mesh geometry={nodes.Text052.geometry} material={nodes.Text052.material} />
        <mesh geometry={nodes.Text053.geometry} material={nodes.Text053.material} />
        <mesh geometry={nodes.Text054.geometry} material={nodes.Text054.material} />
        <mesh geometry={nodes.Text055.geometry} material={nodes.Text055.material} />
        <mesh geometry={nodes.Text056.geometry} material={nodes.Text056.material} />
        <mesh geometry={nodes.Text057.geometry} material={nodes.Text057.material} />
        <mesh geometry={nodes.Text058.geometry} material={nodes.Text058.material} />
        <mesh geometry={nodes.Text059.geometry} material={nodes.Text059.material} />
        <mesh geometry={nodes.Text060.geometry} material={nodes.Text060.material} />
        <mesh geometry={nodes.Text061.geometry} material={nodes.Text061.material} />
        <mesh geometry={nodes.Text062.geometry} material={nodes.Text062.material} />
        <mesh geometry={nodes.Text063.geometry} material={nodes.Text063.material} />
        <mesh geometry={nodes.Text065.geometry} material={nodes.Text065.material} />
        <mesh geometry={nodes.Text066.geometry} material={nodes.Text066.material} />
        <mesh geometry={nodes.Text067.geometry} material={nodes.Text067.material} />
        <mesh geometry={nodes.Text068.geometry} material={nodes.Text068.material} />
        <mesh geometry={nodes.Text069.geometry} material={nodes.Text069.material} />
        <mesh geometry={nodes.Text070.geometry} material={nodes.Text070.material} />
        <mesh geometry={nodes.Text071.geometry} material={nodes.Text071.material} />
        <mesh geometry={nodes.Text072.geometry} material={nodes.Text072.material} />
        <mesh geometry={nodes.Text073.geometry} material={nodes.Text073.material} />
        <mesh geometry={nodes.Text074.geometry} material={nodes.Text074.material} />
        <mesh geometry={nodes.Text075.geometry} material={nodes.Text075.material} />
        <mesh geometry={nodes.Text076.geometry} material={nodes.Text076.material} />
        <mesh geometry={nodes.Text077.geometry} material={nodes.Text077.material} />
        <mesh geometry={nodes.Text078.geometry} material={nodes.Text078.material} />
        <mesh geometry={nodes.Text079.geometry} material={nodes.Text079.material} />
        <mesh geometry={nodes.Text080.geometry} material={nodes.Text080.material} />
        <mesh geometry={nodes.Text081.geometry} material={nodes.Text081.material} />
        <mesh geometry={nodes.Text082.geometry} material={nodes.Text082.material} />
        <mesh geometry={nodes.Text083.geometry} material={nodes.Text083.material} />
        <mesh geometry={nodes.Text084.geometry} material={nodes.Text084.material} />
        <mesh geometry={nodes.Text086.geometry} material={nodes.Text086.material} />
        <mesh geometry={nodes.Text087.geometry} material={nodes.Text087.material} />
        <mesh geometry={nodes.Text090.geometry} material={nodes.Text090.material} />
        <mesh geometry={nodes.Text091.geometry} material={nodes.Text091.material} />
        <mesh geometry={nodes.Text092.geometry} material={nodes.Text092.material} />
        <mesh geometry={nodes.Text093.geometry} material={nodes.Text093.material} />
        <mesh geometry={nodes.Text094.geometry} material={nodes.Text094.material} />
        <mesh geometry={nodes.Text095.geometry} material={nodes.Text095.material} />
        <mesh geometry={nodes.Text096.geometry} material={nodes.Text096.material} />
        <mesh geometry={nodes.Text098.geometry} material={nodes.Text098.material} />
        <mesh geometry={nodes.Text099.geometry} material={nodes.Text099.material} />
        <mesh geometry={nodes.Text100.geometry} material={nodes.Text100.material} />
        <mesh geometry={nodes.Text101.geometry} material={nodes.Text101.material} />
        <mesh geometry={nodes.Text102.geometry} material={nodes.Text102.material} />
        <mesh geometry={nodes.Text104.geometry} material={nodes.Text104.material} />
        <mesh geometry={nodes.Text105.geometry} material={nodes.Text105.material} />
        <mesh geometry={nodes.Text106.geometry} material={nodes.Text106.material} />
        <mesh geometry={nodes.Text108.geometry} material={nodes.Text108.material} />
        <mesh geometry={nodes.Text109.geometry} material={nodes.Text109.material} />
        <mesh geometry={nodes.Text110.geometry} material={nodes.Text110.material} />
        <mesh geometry={nodes.Text111.geometry} material={nodes.Text111.material} />
        <mesh geometry={nodes.Text112.geometry} material={nodes.Text112.material} />
        <mesh geometry={nodes.Text113.geometry} material={nodes.Text113.material} />
        <mesh geometry={nodes.Text114.geometry} material={nodes.Text114.material} />
        <mesh geometry={nodes.Text115.geometry} material={nodes.Text115.material} />
        <mesh geometry={nodes.Text116.geometry} material={nodes.Text116.material} />
        <mesh geometry={nodes.Text118.geometry} material={nodes.Text118.material} />
        <mesh geometry={nodes.Text119.geometry} material={nodes.Text119.material} />
        <mesh geometry={nodes.Text120.geometry} material={nodes.Text120.material} />
        <mesh geometry={nodes.Text121.geometry} material={nodes.Text121.material} />
        <mesh geometry={nodes.Text122.geometry} material={nodes.Text122.material} />
        <mesh geometry={nodes.Text124.geometry} material={nodes.Text124.material} />
        <mesh geometry={nodes.Text125.geometry} material={nodes.Text125.material} />
        <mesh geometry={nodes.Text126.geometry} material={nodes.Text126.material} />
        <mesh geometry={nodes.Text128.geometry} material={nodes.Text128.material} />
        <mesh geometry={nodes.Text129.geometry} material={nodes.Text129.material} />
        <mesh geometry={nodes.Text130.geometry} material={nodes.Text130.material} />
        <mesh geometry={nodes.Text131.geometry} material={nodes.Text131.material} />
        <mesh geometry={nodes.Text132.geometry} material={nodes.Text132.material} />
        <mesh geometry={nodes.Text133.geometry} material={nodes.Text133.material} />
        <mesh geometry={nodes.Text134.geometry} material={nodes.Text134.material} />
        <mesh geometry={nodes.Text135.geometry} material={nodes.Text135.material} />
        <mesh geometry={nodes.Text136.geometry} material={nodes.Text136.material} />
        <mesh geometry={nodes.Text137.geometry} material={nodes.Text137.material} />
        <mesh geometry={nodes.Text138.geometry} material={nodes.Text138.material} />
        <mesh geometry={nodes.Text139.geometry} material={nodes.Text139.material} />
        <mesh geometry={nodes.Text140.geometry} material={nodes.Text140.material} />
        <mesh geometry={nodes.Text141.geometry} material={nodes.Text141.material} />
        <mesh geometry={nodes.Text142.geometry} material={nodes.Text142.material} />
        <mesh geometry={nodes.Text143.geometry} material={nodes.Text143.material} />
        <mesh geometry={nodes.Text144.geometry} material={nodes.Text144.material} />
        <mesh geometry={nodes.Text145.geometry} material={nodes.Text145.material} />
        <mesh geometry={nodes.Text146.geometry} material={nodes.Text146.material} />
        <mesh geometry={nodes.Text147.geometry} material={nodes.Text147.material} />
        <mesh geometry={nodes.Text148.geometry} material={nodes.Text148.material} />
        <mesh geometry={nodes.Text149.geometry} material={nodes.Text149.material} />
        <mesh geometry={nodes.Text150.geometry} material={nodes.Text150.material} />
        <mesh geometry={nodes.Text151.geometry} material={nodes.Text151.material} />
        <mesh geometry={nodes.Text152.geometry} material={nodes.Text152.material} />
        <mesh geometry={nodes.Text153.geometry} material={nodes.Text153.material} />
        <mesh geometry={nodes.Text154.geometry} material={nodes.Text154.material} />
        <mesh geometry={nodes.Text155.geometry} material={nodes.Text155.material} />
        <mesh geometry={nodes.Text157.geometry} material={nodes.Text157.material} />
        <mesh geometry={nodes.Text158.geometry} material={nodes.Text158.material} />
        <mesh geometry={nodes.Text159.geometry} material={nodes.Text159.material} />
        <mesh geometry={nodes.Text160.geometry} material={nodes.Text160.material} />
        <mesh geometry={nodes.Text161.geometry} material={nodes.Text161.material} />
        <mesh geometry={nodes.Text162.geometry} material={nodes.Text162.material} />
        <mesh geometry={nodes.Text163.geometry} material={nodes.Text163.material} />
        <mesh geometry={nodes.Text164.geometry} material={nodes.Text164.material} />
        <mesh geometry={nodes.Text165.geometry} material={nodes.Text165.material} />
        <mesh geometry={nodes.Text166.geometry} material={nodes.Text166.material} />
        <mesh geometry={nodes.Text167.geometry} material={nodes.Text167.material} />
        <mesh geometry={nodes.Text168.geometry} material={nodes.Text168.material} />
        <mesh geometry={nodes.Text169.geometry} material={nodes.Text169.material} />
        <mesh geometry={nodes.Text170.geometry} material={nodes.Text170.material} />
        <mesh geometry={nodes.Text171.geometry} material={nodes.Text171.material} />
        <mesh geometry={nodes.Text172.geometry} material={nodes.Text172.material} />
        <mesh geometry={nodes.Text173.geometry} material={nodes.Text173.material} />
        <mesh geometry={nodes.Text174.geometry} material={nodes.Text174.material} />
        <mesh geometry={nodes.Text175.geometry} material={nodes.Text175.material} />
        <mesh geometry={nodes.Text176.geometry} material={nodes.Text176.material} />
        <mesh geometry={nodes.Text177.geometry} material={nodes.Text177.material} />
        <mesh geometry={nodes.Text178.geometry} material={nodes.Text178.material} />
        <mesh geometry={nodes.Text179.geometry} material={nodes.Text179.material} />
        <mesh geometry={nodes.Text180.geometry} material={nodes.Text180.material} />
        <mesh geometry={nodes.Text181.geometry} material={nodes.Text181.material} />
        <mesh geometry={nodes.Text182.geometry} material={nodes.Text182.material} />
        <mesh geometry={nodes.Text183.geometry} material={nodes.Text183.material} />
        <mesh geometry={nodes.Text184.geometry} material={nodes.Text184.material} />
        <mesh geometry={nodes.Text185.geometry} material={nodes.Text185.material} />
        <mesh geometry={nodes.Text186.geometry} material={nodes.Text186.material} />
        <mesh geometry={nodes.Text187.geometry} material={nodes.Text187.material} />
        <mesh geometry={nodes.Text188.geometry} material={nodes.Text188.material} />
        <mesh geometry={nodes.Text189.geometry} material={nodes.Text189.material} />
        <mesh geometry={nodes.Text190.geometry} material={nodes.Text190.material} />
        <mesh geometry={nodes.Text191.geometry} material={nodes.Text191.material} />
        <mesh geometry={nodes.Text192.geometry} material={nodes.Text192.material} />
        <mesh geometry={nodes.Text193.geometry} material={nodes.Text193.material} />
        <mesh geometry={nodes.Text194.geometry} material={nodes.Text194.material} />
        <mesh geometry={nodes.Text195.geometry} material={nodes.Text195.material} />
        <mesh geometry={nodes.Text196.geometry} material={nodes.Text196.material} />
        <mesh geometry={nodes.Text197.geometry} material={nodes.Text197.material} />
        <mesh geometry={nodes.Text198.geometry} material={nodes.Text198.material} />
        <mesh geometry={nodes.Text199.geometry} material={nodes.Text199.material} />
        <mesh geometry={nodes.Text200.geometry} material={nodes.Text200.material} />
        <mesh geometry={nodes.Text201.geometry} material={nodes.Text201.material} />
        <mesh geometry={nodes.Text202.geometry} material={nodes.Text202.material} />
        <mesh geometry={nodes.Text203.geometry} material={nodes.Text203.material} />
        <mesh geometry={nodes.Text204.geometry} material={nodes.Text204.material} />
        <mesh geometry={nodes.Text205.geometry} material={nodes.Text205.material} />
        <mesh geometry={nodes.Text206.geometry} material={nodes.Text206.material} />
        <mesh geometry={nodes.Text207.geometry} material={nodes.Text207.material} />
        <mesh geometry={nodes.Text208.geometry} material={nodes.Text208.material} />
        <mesh geometry={nodes.Text209.geometry} material={nodes.Text209.material} />
        <mesh geometry={nodes.Text210.geometry} material={nodes.Text210.material} />
        <mesh geometry={nodes.Text211.geometry} material={nodes.Text211.material} />
        <mesh geometry={nodes.Text212.geometry} material={nodes.Text212.material} />
        <mesh geometry={nodes.Text213.geometry} material={nodes.Text213.material} />
        <mesh geometry={nodes.Text214.geometry} material={nodes.Text214.material} />
        <mesh geometry={nodes.Text215.geometry} material={nodes.Text215.material} />
        <mesh geometry={nodes.Text216.geometry} material={nodes.Text216.material} />
        <mesh geometry={nodes.Text217.geometry} material={nodes.Text217.material} />
        <mesh geometry={nodes.Text218.geometry} material={nodes.Text218.material} />
        <mesh geometry={nodes.Text219.geometry} material={nodes.Text219.material} />
        <mesh geometry={nodes.Text220.geometry} material={nodes.Text220.material} />
        <mesh geometry={nodes.Text221.geometry} material={nodes.Text221.material} />
        <mesh geometry={nodes.Text222.geometry} material={nodes.Text222.material} />
        <mesh geometry={nodes.Text223.geometry} material={nodes.Text223.material} />
        <mesh geometry={nodes.Text224.geometry} material={nodes.Text224.material} />
        <mesh geometry={nodes.Text225.geometry} material={nodes.Text225.material} />
        <mesh geometry={nodes.Text226.geometry} material={nodes.Text226.material} />
        <mesh geometry={nodes.Text227.geometry} material={nodes.Text227.material} />
        <mesh geometry={nodes.Text228.geometry} material={nodes.Text228.material} />
        <mesh geometry={nodes.Text229.geometry} material={nodes.Text229.material} />
        <mesh geometry={nodes.Text230.geometry} material={nodes.Text230.material} />
        <mesh geometry={nodes.Text231.geometry} material={nodes.Text231.material} />
        <mesh geometry={nodes.Text232.geometry} material={nodes.Text232.material} />
        <mesh geometry={nodes.Text233.geometry} material={nodes.Text233.material} />
        <mesh geometry={nodes.Text234.geometry} material={nodes.Text234.material} />
        <mesh geometry={nodes.Text235.geometry} material={nodes.Text235.material} />
        <mesh geometry={nodes.Text236.geometry} material={nodes.Text236.material} />
        <mesh geometry={nodes.Text237.geometry} material={nodes.Text237.material} />
        <mesh geometry={nodes.Text238.geometry} material={nodes.Text238.material} />
        <mesh geometry={nodes.Text239.geometry} material={nodes.Text239.material} />
        <mesh geometry={nodes.Text240.geometry} material={nodes.Text240.material} />
        <mesh geometry={nodes.Text241.geometry} material={nodes.Text241.material} />
        <mesh geometry={nodes.Text242.geometry} material={nodes.Text242.material} />
        <mesh geometry={nodes.Text243.geometry} material={nodes.Text243.material} />
        <mesh geometry={nodes.Text244.geometry} material={nodes.Text244.material} />
        <mesh geometry={nodes.Text245.geometry} material={nodes.Text245.material} />
        <mesh geometry={nodes.Text246.geometry} material={nodes.Text246.material} />
        <mesh geometry={nodes.Text247.geometry} material={nodes.Text247.material} />
        <mesh geometry={nodes.Text248.geometry} material={nodes.Text248.material} />
        <mesh geometry={nodes.Text249.geometry} material={nodes.Text249.material} />
        <mesh geometry={nodes.Text250.geometry} material={nodes.Text250.material} />
        <mesh geometry={nodes.Text251.geometry} material={nodes.Text251.material} />
        <mesh geometry={nodes.Text252.geometry} material={nodes.Text252.material} />
        <mesh geometry={nodes.Text253.geometry} material={nodes.Text253.material} />
        <mesh geometry={nodes.Text254.geometry} material={nodes.Text254.material} />
        <mesh geometry={nodes.Text255.geometry} material={nodes.Text255.material} />
        <mesh geometry={nodes.Text256.geometry} material={nodes.Text256.material} />
        <mesh geometry={nodes.Text257.geometry} material={nodes.Text257.material} />
        <mesh geometry={nodes.Text258.geometry} material={nodes.Text258.material} />
        <mesh geometry={nodes.Text259.geometry} material={nodes.Text259.material} />
        <mesh geometry={nodes.Text260.geometry} material={nodes.Text260.material} />
        <mesh geometry={nodes.Text261.geometry} material={nodes.Text261.material} />
        <mesh geometry={nodes.Text262.geometry} material={nodes.Text262.material} />
        <mesh geometry={nodes.Text263.geometry} material={nodes.Text263.material} />
        <mesh geometry={nodes.Text264.geometry} material={nodes.Text264.material} />
        <mesh geometry={nodes.Text265.geometry} material={nodes.Text265.material} />
        <mesh geometry={nodes.Text266.geometry} material={nodes.Text266.material} />
        <mesh geometry={nodes.Text267.geometry} material={nodes.Text267.material} />
        <mesh geometry={nodes.Text268.geometry} material={nodes.Text268.material} />
        <mesh geometry={nodes.Text269.geometry} material={nodes.Text269.material} />
        <mesh geometry={nodes.Text270.geometry} material={nodes.Text270.material} />
        <mesh geometry={nodes.Text271.geometry} material={nodes.Text271.material} />
        <mesh geometry={nodes.Text272.geometry} material={nodes.Text272.material} />
        <mesh geometry={nodes.Text273.geometry} material={nodes.Text273.material} />
        <mesh geometry={nodes.Text274.geometry} material={nodes.Text274.material} />
        <mesh geometry={nodes.Text275.geometry} material={nodes.Text275.material} />
        <mesh geometry={nodes.Text276.geometry} material={nodes.Text276.material} />
        <mesh geometry={nodes.Text277.geometry} material={nodes.Text277.material} />
        <mesh geometry={nodes.Text278.geometry} material={nodes.Text278.material} />
        <mesh geometry={nodes.Text279.geometry} material={nodes.Text279.material} />
        <mesh geometry={nodes.Text280.geometry} material={nodes.Text280.material} />
        <mesh geometry={nodes.Text281.geometry} material={nodes.Text281.material} />
        <mesh geometry={nodes.Text282.geometry} material={nodes.Text282.material} />
        <mesh geometry={nodes.Text283.geometry} material={nodes.Text283.material} />
        <mesh geometry={nodes.Text284.geometry} material={nodes.Text284.material} />
        <mesh geometry={nodes.Text285.geometry} material={nodes.Text285.material} />
        <mesh geometry={nodes.Text286.geometry} material={nodes.Text286.material} />
        <mesh geometry={nodes.Text287.geometry} material={nodes.Text287.material} />
        <mesh geometry={nodes.Text288.geometry} material={nodes.Text288.material} />
        <mesh geometry={nodes.Text289.geometry} material={nodes.Text289.material} />
        <mesh geometry={nodes.Text290.geometry} material={nodes.Text290.material} />
        <mesh geometry={nodes.Text291.geometry} material={nodes.Text291.material} />
        <mesh geometry={nodes.Text292.geometry} material={nodes.Text292.material} />
        <mesh geometry={nodes.Text293.geometry} material={nodes.Text293.material} />
        <mesh geometry={nodes.Text294.geometry} material={nodes.Text294.material} />
        <mesh geometry={nodes.Text295.geometry} material={nodes.Text295.material} />
        <mesh geometry={nodes.Text296.geometry} material={nodes.Text296.material} />
        <mesh geometry={nodes.Text297.geometry} material={nodes.Text297.material} />
        <mesh geometry={nodes.Text298.geometry} material={nodes.Text298.material} />
        <mesh geometry={nodes.Text299.geometry} material={nodes.Text299.material} />
        <mesh geometry={nodes.Text300.geometry} material={nodes.Text300.material} />
        <mesh geometry={nodes.Text301.geometry} material={nodes.Text301.material} />
        <mesh geometry={nodes.Text302.geometry} material={nodes.Text302.material} />
        <mesh geometry={nodes.Text303.geometry} material={nodes.Text303.material} />
        <mesh geometry={nodes.Text304.geometry} material={nodes.Text304.material} />
        <mesh geometry={nodes.Text305.geometry} material={nodes.Text305.material} />
        <mesh geometry={nodes.Text306.geometry} material={nodes.Text306.material} />
        <mesh geometry={nodes.Text307.geometry} material={nodes.Text307.material} />
        <mesh geometry={nodes.Text308.geometry} material={nodes.Text308.material} />
        <mesh geometry={nodes.Text309.geometry} material={nodes.Text309.material} />
        <mesh geometry={nodes.Text310.geometry} material={nodes.Text310.material} />
        <mesh geometry={nodes.Text311.geometry} material={nodes.Text311.material} />
        <mesh geometry={nodes.Text312.geometry} material={nodes.Text312.material} />
        <mesh geometry={nodes.Text313.geometry} material={nodes.Text313.material} />
        <mesh geometry={nodes.Text314.geometry} material={nodes.Text314.material} />
        <mesh geometry={nodes.Text315.geometry} material={nodes.Text315.material} />
        <mesh geometry={nodes.Text316.geometry} material={nodes.Text316.material} />
        <mesh geometry={nodes.Text317.geometry} material={nodes.Text317.material} />
        <mesh geometry={nodes.Text318.geometry} material={nodes.Text318.material} />
        <mesh geometry={nodes.Text319.geometry} material={nodes.Text319.material} />
        <mesh geometry={nodes.Text320.geometry} material={nodes.Text320.material} />
        <mesh geometry={nodes.Text321.geometry} material={nodes.Text321.material} />
        <mesh geometry={nodes.Text322.geometry} material={nodes.Text322.material} />
        <mesh geometry={nodes.Text323.geometry} material={nodes.Text323.material} />
        <mesh geometry={nodes.Text324.geometry} material={nodes.Text324.material} />
        <mesh geometry={nodes.Text325.geometry} material={nodes.Text325.material} />
        <mesh geometry={nodes.Text326.geometry} material={nodes.Text326.material} />
        <mesh geometry={nodes.Text327.geometry} material={nodes.Text327.material} />
        <mesh geometry={nodes.Text328.geometry} material={nodes.Text328.material} />
        <mesh geometry={nodes.Text329.geometry} material={nodes.Text329.material} />
        <mesh geometry={nodes.Text330.geometry} material={nodes.Text330.material} />
        <mesh geometry={nodes.Text331.geometry} material={nodes.Text331.material} />
        <mesh geometry={nodes.Text332.geometry} material={nodes.Text332.material} />
        <mesh geometry={nodes.Text333.geometry} material={nodes.Text333.material} />
        <mesh geometry={nodes.Text334.geometry} material={nodes.Text334.material} />
        <mesh geometry={nodes.Text335.geometry} material={nodes.Text335.material} />
        <mesh geometry={nodes.Text336.geometry} material={nodes.Text336.material} />
        <mesh geometry={nodes.Text337.geometry} material={nodes.Text337.material} />
        <mesh geometry={nodes.Text338.geometry} material={nodes.Text338.material} />
        <mesh geometry={nodes.Text339.geometry} material={nodes.Text339.material} />
        <mesh geometry={nodes.Text340.geometry} material={nodes.Text340.material} />
        <mesh geometry={nodes.Text341.geometry} material={nodes.Text341.material} />
        <mesh geometry={nodes.Text342.geometry} material={nodes.Text342.material} />
        <mesh geometry={nodes.Text343.geometry} material={nodes.Text343.material} />
        <mesh geometry={nodes.Text344.geometry} material={nodes.Text344.material} />
        <mesh geometry={nodes.Text345.geometry} material={nodes.Text345.material} />
        <mesh geometry={nodes.Text346.geometry} material={nodes.Text346.material} />
        <mesh geometry={nodes.Text347.geometry} material={nodes.Text347.material} />
        <mesh geometry={nodes.Text348.geometry} material={nodes.Text348.material} />
        <mesh geometry={nodes.Text349.geometry} material={nodes.Text349.material} />
        <mesh geometry={nodes.Text350.geometry} material={nodes.Text350.material} />
        <mesh geometry={nodes.Text351.geometry} material={nodes.Text351.material} />
        <mesh geometry={nodes.Text352.geometry} material={nodes.Text352.material} />
        <mesh geometry={nodes.Text353.geometry} material={nodes.Text353.material} />
        <mesh geometry={nodes.Text354.geometry} material={nodes.Text354.material} />
        <mesh geometry={nodes.Text355.geometry} material={nodes.Text355.material} />
        <mesh geometry={nodes.Text356.geometry} material={nodes.Text356.material} />
        <mesh geometry={nodes.Text357.geometry} material={nodes.Text357.material} />
        <mesh geometry={nodes.Text358.geometry} material={nodes.Text358.material} />
        <mesh geometry={nodes.Text359.geometry} material={nodes.Text359.material} />
        <mesh geometry={nodes.Text360.geometry} material={nodes.Text360.material} />
        <mesh geometry={nodes.Text361.geometry} material={nodes.Text361.material} />
        <mesh geometry={nodes.Text362.geometry} material={nodes.Text362.material} />
        <mesh geometry={nodes.Text363.geometry} material={nodes.Text363.material} />
        <mesh geometry={nodes.Text364.geometry} material={nodes.Text364.material} />
        <mesh geometry={nodes.Text365.geometry} material={nodes.Text365.material} />
        <mesh geometry={nodes.Text366.geometry} material={nodes.Text366.material} />
        <mesh geometry={nodes.Text367.geometry} material={nodes.Text367.material} />
        <mesh geometry={nodes.Text368.geometry} material={nodes.Text368.material} />
        <mesh geometry={nodes.Text369.geometry} material={nodes.Text369.material} />
        <mesh geometry={nodes.Text370.geometry} material={nodes.Text370.material} />
        <mesh geometry={nodes.Text371.geometry} material={nodes.Text371.material} />
        <mesh geometry={nodes.Text372.geometry} material={nodes.Text372.material} />
        <mesh geometry={nodes.Text373.geometry} material={nodes.Text373.material} />
        <mesh geometry={nodes.Text374.geometry} material={nodes.Text374.material} />
        <mesh geometry={nodes.Text375.geometry} material={nodes.Text375.material} />
        <mesh geometry={nodes.Text376.geometry} material={nodes.Text376.material} />
        <mesh geometry={nodes.Text377.geometry} material={nodes.Text377.material} />
        <mesh geometry={nodes.Text378.geometry} material={nodes.Text378.material} />
        <mesh geometry={nodes.Text379.geometry} material={nodes.Text379.material} />
        <mesh geometry={nodes.Text380.geometry} material={nodes.Text380.material} />
        <mesh geometry={nodes.Text381.geometry} material={nodes.Text381.material} />
        <mesh geometry={nodes.Text382.geometry} material={nodes.Text382.material} />
        <mesh geometry={nodes.Text383.geometry} material={nodes.Text383.material} />
        <mesh geometry={nodes.Text384.geometry} material={nodes.Text384.material} />
        <mesh geometry={nodes.Text385.geometry} material={nodes.Text385.material} />
        <mesh geometry={nodes.Text386.geometry} material={nodes.Text386.material} />
        <mesh geometry={nodes.Text387.geometry} material={nodes.Text387.material} />
        <mesh geometry={nodes.Text388.geometry} material={nodes.Text388.material} />
        <mesh geometry={nodes.Text389.geometry} material={nodes.Text389.material} />
        <mesh geometry={nodes.Text390.geometry} material={nodes.Text390.material} />
        <mesh geometry={nodes.Text391.geometry} material={nodes.Text391.material} />
        <mesh geometry={nodes.Text392.geometry} material={nodes.Text392.material} />
        <mesh geometry={nodes.Text393.geometry} material={nodes.Text393.material} />
        <mesh geometry={nodes.Text394.geometry} material={nodes.Text394.material} />
        <mesh geometry={nodes.Text395.geometry} material={nodes.Text395.material} />
        <mesh geometry={nodes.Text396.geometry} material={nodes.Text396.material} />
        <mesh geometry={nodes.Text397.geometry} material={nodes.Text397.material} />
        <mesh geometry={nodes.Text398.geometry} material={nodes.Text398.material} />
        <mesh geometry={nodes.Text399.geometry} material={nodes.Text399.material} />
        <mesh geometry={nodes.Text400.geometry} material={nodes.Text400.material} />
        <mesh geometry={nodes.Text401.geometry} material={nodes.Text401.material} />
        <mesh geometry={nodes.Text402.geometry} material={nodes.Text402.material} />
        <mesh geometry={nodes.Text403.geometry} material={nodes.Text403.material} />
        <mesh geometry={nodes.Text404.geometry} material={nodes.Text404.material} />
        <mesh geometry={nodes.Text405.geometry} material={nodes.Text405.material} />
        <mesh geometry={nodes.Text406.geometry} material={nodes.Text406.material} />
        <mesh geometry={nodes.Text407.geometry} material={nodes.Text407.material} />
        <mesh geometry={nodes.Text408.geometry} material={nodes.Text408.material} />
        <mesh geometry={nodes.Text409.geometry} material={nodes.Text409.material} />
        <mesh geometry={nodes.Text410.geometry} material={nodes.Text410.material} />
        <mesh geometry={nodes.Text411.geometry} material={nodes.Text411.material} />
        <mesh geometry={nodes.Text412.geometry} material={nodes.Text412.material} />
        <mesh geometry={nodes.Text413.geometry} material={nodes.Text413.material} />
        <mesh geometry={nodes.Text414.geometry} material={nodes.Text414.material} />
        <mesh geometry={nodes.Text415.geometry} material={nodes.Text415.material} />
        <mesh geometry={nodes.Text416.geometry} material={nodes.Text416.material} />
        <mesh geometry={nodes.Text417.geometry} material={nodes.Text417.material} />
        <mesh geometry={nodes.Text418.geometry} material={nodes.Text418.material} />
        <mesh geometry={nodes.Text419.geometry} material={nodes.Text419.material} />
        <mesh geometry={nodes.Text420.geometry} material={nodes.Text420.material} />
        <mesh geometry={nodes.Text421.geometry} material={nodes.Text421.material} />
        <mesh geometry={nodes.Text422.geometry} material={nodes.Text422.material} />
        <mesh geometry={nodes.Text423.geometry} material={nodes.Text423.material} />
        <mesh geometry={nodes.Text424.geometry} material={nodes.Text424.material} />
        <mesh geometry={nodes.Text425.geometry} material={nodes.Text425.material} />
        <mesh geometry={nodes.Text426.geometry} material={nodes.Text426.material} />
        <mesh geometry={nodes.Text427.geometry} material={nodes.Text427.material} />
        <mesh geometry={nodes.Text428.geometry} material={nodes.Text428.material} />
        <mesh geometry={nodes.Text429.geometry} material={nodes.Text429.material} />
        <mesh geometry={nodes.Text430.geometry} material={nodes.Text430.material} />
        <mesh geometry={nodes.Text431.geometry} material={nodes.Text431.material} />
        <mesh geometry={nodes.Text432.geometry} material={nodes.Text432.material} />
        <mesh geometry={nodes.Text433.geometry} material={nodes.Text433.material} />
        <mesh geometry={nodes.Text434.geometry} material={nodes.Text434.material} />
        <mesh geometry={nodes.Text435.geometry} material={nodes.Text435.material} />
        <mesh geometry={nodes.Text436.geometry} material={nodes.Text436.material} />
        <mesh geometry={nodes.Text437.geometry} material={nodes.Text437.material} />
        <mesh geometry={nodes.Text438.geometry} material={nodes.Text438.material} />
        <mesh geometry={nodes.Text439.geometry} material={nodes.Text439.material} />
        <mesh geometry={nodes.Text440.geometry} material={nodes.Text440.material} />
        <mesh geometry={nodes.Text441.geometry} material={nodes.Text441.material} />
        <mesh geometry={nodes.Text442.geometry} material={nodes.Text442.material} />
        <mesh geometry={nodes.Text443.geometry} material={nodes.Text443.material} />
        <mesh geometry={nodes.Text444.geometry} material={nodes.Text444.material} />
        <mesh geometry={nodes.Text445.geometry} material={nodes.Text445.material} />
        <mesh geometry={nodes.Text446.geometry} material={nodes.Text446.material} />
        <mesh geometry={nodes.Text448.geometry} material={nodes.Text448.material} />
        <mesh geometry={nodes.Text449.geometry} material={nodes.Text449.material} />
        <mesh geometry={nodes.Text450.geometry} material={nodes.Text450.material} />
        <mesh geometry={nodes.Text451.geometry} material={nodes.Text451.material} />
        <mesh geometry={nodes.Text452.geometry} material={nodes.Text452.material} />
        <mesh geometry={nodes.Text453.geometry} material={nodes.Text453.material} />
        <mesh geometry={nodes.Text454.geometry} material={nodes.Text454.material} />
        <mesh geometry={nodes.Text455.geometry} material={nodes.Text455.material} />
        <mesh geometry={nodes.Text456.geometry} material={nodes.Text456.material} />
        <mesh geometry={nodes.Text457.geometry} material={nodes.Text457.material} />
        <mesh geometry={nodes.Text458.geometry} material={nodes.Text458.material} />
        <mesh geometry={nodes.Text459.geometry} material={nodes.Text459.material} />
        <mesh geometry={nodes.Text460.geometry} material={nodes.Text460.material} />
        <mesh geometry={nodes.Text461.geometry} material={nodes.Text461.material} />
        <mesh geometry={nodes.Text462.geometry} material={nodes.Text462.material} />
        <mesh geometry={nodes.Text463.geometry} material={nodes.Text463.material} />
        <mesh geometry={nodes.Text464.geometry} material={nodes.Text464.material} />
        <mesh geometry={nodes.Text465.geometry} material={nodes.Text465.material} />
        <mesh geometry={nodes.Text466.geometry} material={nodes.Text466.material} />
        <mesh geometry={nodes.Text467.geometry} material={nodes.Text467.material} />
        <mesh geometry={nodes.Text468.geometry} material={nodes.Text468.material} />
        <mesh geometry={nodes.Text469.geometry} material={nodes.Text469.material} />
        <mesh geometry={nodes.Text470.geometry} material={nodes.Text470.material} />
        <mesh geometry={nodes.Text471.geometry} material={nodes.Text471.material} />
        <mesh geometry={nodes.Text475.geometry} material={nodes.Text475.material} />
        <mesh geometry={nodes.Text476.geometry} material={nodes.Text476.material} />
        <mesh geometry={nodes.Text477.geometry} material={nodes.Text477.material} />
        <mesh geometry={nodes.Text478.geometry} material={nodes.Text478.material} />
        <mesh geometry={nodes.Text479.geometry} material={nodes.Text479.material} />
        <mesh geometry={nodes.Text480.geometry} material={nodes.Text480.material} />
        <mesh geometry={nodes.Text481.geometry} material={nodes.Text481.material} />
        <mesh geometry={nodes.Text482.geometry} material={nodes.Text482.material} />
        <mesh geometry={nodes.Text483.geometry} material={nodes.Text483.material} />
        <mesh geometry={nodes.Text484.geometry} material={nodes.Text484.material} />
        <mesh geometry={nodes.Text485.geometry} material={nodes.Text485.material} />
        <mesh geometry={nodes.Text486.geometry} material={nodes.Text486.material} />
        <mesh geometry={nodes.Text487.geometry} material={nodes.Text487.material} />
        <mesh geometry={nodes.Text488.geometry} material={nodes.Text488.material} />
        <mesh geometry={nodes.Text489.geometry} material={nodes.Text489.material} />
        <mesh geometry={nodes.Text490.geometry} material={nodes.Text490.material} />
        <mesh geometry={nodes.Text491.geometry} material={nodes.Text491.material} />
        <mesh geometry={nodes.Text492.geometry} material={nodes.Text492.material} />
        <mesh geometry={nodes.Text493.geometry} material={nodes.Text493.material} />
        <mesh geometry={nodes.Text494.geometry} material={nodes.Text494.material} />
        <mesh geometry={nodes.Text495.geometry} material={nodes.Text495.material} />
        <mesh geometry={nodes.Text496.geometry} material={nodes.Text496.material} />
        <mesh geometry={nodes.Text497.geometry} material={nodes.Text497.material} />
        <mesh geometry={nodes.Text498.geometry} material={nodes.Text498.material} />
        <mesh geometry={nodes.Text499.geometry} material={nodes.Text499.material} />
        <mesh geometry={nodes.Text501.geometry} material={nodes.Text501.material} />
        <mesh geometry={nodes.Text502.geometry} material={nodes.Text502.material} />
        <mesh geometry={nodes.Text503.geometry} material={nodes.Text503.material} />
        <mesh geometry={nodes.Text504.geometry} material={nodes.Text504.material} />
        <mesh geometry={nodes.Text505.geometry} material={nodes.Text505.material} />
        <mesh geometry={nodes.Text506.geometry} material={nodes.Text506.material} />
        <mesh geometry={nodes.Text507.geometry} material={nodes.Text507.material} />
        <mesh geometry={nodes.Text508.geometry} material={nodes.Text508.material} />
        <mesh geometry={nodes.Text509.geometry} material={nodes.Text509.material} />
        <mesh geometry={nodes.Text510.geometry} material={nodes.Text510.material} />
        <mesh geometry={nodes.Text511.geometry} material={nodes.Text511.material} />
        <mesh geometry={nodes.Text512.geometry} material={nodes.Text512.material} />
        <mesh geometry={nodes.Text513.geometry} material={nodes.Text513.material} />
        <mesh geometry={nodes.Text514.geometry} material={nodes.Text514.material} />
        <mesh geometry={nodes.Text515.geometry} material={nodes.Text515.material} />
        <mesh geometry={nodes.Text516.geometry} material={nodes.Text516.material} />
        <mesh geometry={nodes.Text517.geometry} material={nodes.Text517.material} />
        <mesh geometry={nodes.Text518.geometry} material={nodes.Text518.material} />
        <mesh geometry={nodes.Text519.geometry} material={nodes.Text519.material} />
        <mesh geometry={nodes.Text520.geometry} material={nodes.Text520.material} />
        <mesh geometry={nodes.Text521.geometry} material={nodes.Text521.material} />
        <mesh geometry={nodes.Text522.geometry} material={nodes.Text522.material} />
        <mesh geometry={nodes.Text526.geometry} material={nodes.Text526.material} />
        <mesh geometry={nodes.Text527.geometry} material={nodes.Text527.material} />
        <mesh geometry={nodes.Text528.geometry} material={nodes.Text528.material} />
        <mesh geometry={nodes.Text529.geometry} material={nodes.Text529.material} />
        <mesh geometry={nodes.Text530.geometry} material={nodes.Text530.material} />
        <mesh geometry={nodes.Text531.geometry} material={nodes.Text531.material} />
        <mesh geometry={nodes.Text532.geometry} material={nodes.Text532.material} />
        <mesh geometry={nodes.Text533.geometry} material={nodes.Text533.material} />
        <mesh geometry={nodes.Text534.geometry} material={nodes.Text534.material} />
        <mesh geometry={nodes.Text535.geometry} material={nodes.Text535.material} />
        <mesh geometry={nodes.Text536.geometry} material={nodes.Text536.material} />
        <mesh geometry={nodes.Text537.geometry} material={nodes.Text537.material} />
        <mesh geometry={nodes.Text538.geometry} material={nodes.Text538.material} />
        <mesh geometry={nodes.Text539.geometry} material={nodes.Text539.material} />
        <mesh geometry={nodes.Text540.geometry} material={nodes.Text540.material} />
        <mesh geometry={nodes.Text541.geometry} material={nodes.Text541.material} />
      </mesh>
    </group>
  )
}

useGLTF.preload(`${import.meta.env.BASE_URL}models/dollar.glb`)
